version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: leatherman
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://billy:leatherman@db:5432/contactdb
    volumes:
      - .:/app